config/routes.rb
Rails.application.routes.draw do  
  resources :sessions, only: [:new, :create, :destroy]  
  get 'signup', to: 'users#new', as: 'signup'  
  get 'login', to: 'sessions#new', as: 'login'  
  get 'logout', to: 'sessions#destroy', as: 'logout'  
  resources :users  
  get 'page/index'  
  root 'page#index' 
  resources :posts do 
    resources :likes 
  end 
end  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :likes, dependent: :destroy
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	 private   
  def current_user   
    User.where(id: session[:user_id]).first   
  end   
  helper_method :current_user   
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :find_post
  before_action :find_like, only: [:destroy]

  def create
	  if already_liked?
	    flash[:notice] = "You can't like more than once"
	  else
	    @post.likes.create(user_id: current_user.id)
	  end
	  redirect_to root_path(@post)
	end

  def destroy
	  if !(already_liked?)
	    flash[:notice] = "Cannot unlike"
	  else
	    @like.destroy
	  end
	  redirect_to root_path(@post)
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end

	def already_liked?
	  Like.where(user_id: current_user.id, post_id:
	  params[:post_id]).exists?
	end

	def find_like
   	@like = @post.likes.find(params[:id])
	end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  	@posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if params[:post].present?
      file = params[:post][:image]
      File.open(Rails.root.join('app','assets','images', file.original_filename), 'wb') do |f|
        f.write(file.read)
      end
      @post.image = file.original_filename
    end
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if params[:post].present? && params[:post][:image].present?
      file = params[:post][:image]
      File.open(Rails.root.join('app','assets','images', file.original_filename), 'wb') do |f|
        f.write(file.read)
      end
      params[:post][:image] = file.original_filename
    end
    if @post.update(post_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:caption,:image, :user_id)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController   
  def new   
  end   
  def create   
    user = User.find_by_email(params[:email])   
    if user && user.authenticate(params[:password])   
      session[:user_id] = user.id   
      redirect_to root_url, notice: 'Logged in!'   
    else   
      render :new   
    end   
  end   
  def destroy   
    session[:user_id] = nil   
    redirect_to root_url, notice: 'Logged out!'   
  end   
end  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
     @user = User.new(user_params)   
    if @user.save   
      session[:user_id] = @user.id   
      redirect_to root_url, notice: 'User successfully created.'   
    else   
      render :new   
    end   
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewInstaApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-light d-flex">
      <div class="container">
        <div class="logo">
          <a class="navbar-brand" href="<%= root_path %>">
            <%= image_tag'instagram.png', style: "width:10%;height:10%" %>
            Instagram
          </a>
          <p class="navbar-text float-right">
            <% if current_user %>  
              Logged in as <%= current_user.email %>.  
              <%= link_to "Log Out", logout_path %>  
            <% else %>  
              <%= link_to "Sign Up", signup_path %> or  
              <%= link_to "Log In", login_path %>  
            <% end %>  
          </p>
        </div>
      </div>
    </nav>
    
    <%= yield %>
  </body>
</html>

app/views/page/index.html.erb
<% if current_user %>
  <div class = "posts-wrapper row">
  	<%= link_to "New Post", new_post_path, style: "float:right;color: red;"%>
		<div class = "post">
      <div class = "post-head">
		<% @posts.each do |post| %>
			<div class = "image text-center">
			 	<%=image_tag post.image,style: "width: 40%"%>
			 </div>
		 	<p class="caption text-center"><%= post.caption%></p>
		 	<div class="text-center edit-links" >
		 		<p><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></p>
		 		<% pre_like = post.likes.find { |like| like.user_id == current_user&.id} %>
				<% if pre_like %>
				  <%= button_to 'Unlike', post_like_path(post, pre_like), method: :delete %>
				<% else %>
				  <%= button_to 'Like', post_likes_path(post), method: :post %>
				<% end %>
		 		<%= link_to 'Edit', edit_post_path(post) %> 
				|
				<%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure, you want to delete this?' } %>
			</div>
		<%end%>
		</div>
	</div>
</div>
<%else%>
	<h5 style="margin-left: 39%;margin-top: 17%;color: #ff0076;">Welcome to my Instagram App</h5>
<%end%>

app/views/posts/_form.html.erb
<div class="form-wrapper">
	<%= form_for @post, html: {multipart: true, class: 'form-horizontal' } do |f| %>
		<div class="form-group ">
			<%= f.file_field :image%>		
		</div>
		<div class="form-group text-center">
			<%= f.text_field :caption,class: 'form-control' %>	
		</div>
		<%= f.hidden_field :user_id,class: 'form-control', value: current_user.id %>
		<div class="form-group text-center">
			<%= f.submit  "Create Post",class: 'btn-success' %>
		</div>
	<%end%>
</div>

app/views/posts/edit.html.erb
<div class="text-center">
  <%= image_tag @post.image,style: "width: 50%"%>
</div>
<div class="form-wrapper">
	<%= form_for @post, html: {multipart: true, class: 'form-horizontal' } do |f| %>
		<div class="form-group ">
			<%= f.file_field :image%>		
		</div>
		<div class="form-group text-center">
			<%= f.text_field :caption,class: 'form-control' %>	
		</div>
		<%= f.hidden_field :user_id,class: 'form-control', value: current_user.id %>
		<div class="form-group text-center">
			<%= f.submit  "Update Post",class: 'btn-success' %>
		</div>
	<%end%>
</div>

app/views/posts/index.html.erb
<%= link_to "New Post", new_post_path, style: "float:right"%> 
<div class = "posts-wrapper row">
	<div class = "post">
      <div class = "post-head">
		<% @posts.each do |post| %>
			<div class = "image text-center">
			 	<%=image_tag post.image,style: "width: 60%"%>
			 </div>
		 	<p class="caption text-center"><%= post.caption%></p>
		 	<div class="text-center edit-links" >
				<%= link_to 'Edit', edit_post_path(post) %> 
				|
				<%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure, you want to delete this?' } %>
			</div>
		<%end%>
		</div>
	</div>
</div>

app/views/posts/new.html.erb
<%= render 'form'%>

app/views/users/_form.html.erb
<div class="form-wrapper">

  <%= form_with(model: user, local: true) do |form| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group ">
      <%= form.label :first_name %>
      <%= form.text_field :first_name %>
    </div>

    <div class="form-group ">
      <%= form.label :last_name %>
      <%= form.text_field :last_name %>
    </div>

    <div class="form-group ">
      <%= form.label :email %>
      <%= form.text_field :email %>
    </div>

    <div class="form-group ">
      <%= form.label :password %>
      <%= form.password_field :password %>
    </div>

    <div class="form-group ">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation %>
    </div>

    <div class="form-group ">
      <%= form.submit %>
    </div>
  <% end %>

</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>